#spiral
import turtle
cass=turtle.Turtle()
cass.color("magenta")
cass.forward(10)
cass.right(90)
cass.forward(20)
cass.right(90)
cass.forward(30)
cass.right(90)
cass.forward(40)
cass.right(90)
cass.forward(50)
cass.right(90)
cass.forward(60)
cass.right(90)
cass.forward(70)
cass.right(90)
cass.forward(80)
cass.right(90)
cass.forward(90)
cass.right(90)
cass.forward(100)

